/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author iker
 */
public class interfazCandidatos extends javax.swing.JFrame {

    /**
     * Creates new form interfazCandidatos
     */
	private Controlador ctrl;
    public interfazCandidatos(Controlador ctrl) {
    	this.ctrl = ctrl;
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagen/logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cont1 = new javax.swing.JButton();
        cont2 = new javax.swing.JButton();
        cont3 = new javax.swing.JButton();
        cand1 = new javax.swing.JButton();
        cand2 = new javax.swing.JButton();
        cand3 = new javax.swing.JButton();
        empresa = new javax.swing.JLabel();
        buscar2 = new javax.swing.JButton();
        buscar1 = new javax.swing.JTextField();
        principal = new javax.swing.JButton();
        crear = new javax.swing.JButton();
        perfil = new javax.swing.JButton();
        menu1 = new javax.swing.JLabel();
        menu2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cont1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/contrato.png"))); // NOI18N
        cont1.setContentAreaFilled(false);
        getContentPane().add(cont1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 30, 30));

        cont2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/contrato.png"))); // NOI18N
        cont2.setContentAreaFilled(false);
        getContentPane().add(cont2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 30, 30));

        cont3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/contrato.png"))); // NOI18N
        cont3.setContentAreaFilled(false);
        getContentPane().add(cont3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 30, 30));

        cand1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cand1.setForeground(new java.awt.Color(0, 0, 153));
        cand1.setText("NOMBRE CANDIDATO 1");
        cand1.setContentAreaFilled(false);
        cand1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cand1ActionPerformed(evt);
            }
        });
        getContentPane().add(cand1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        cand2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cand2.setForeground(new java.awt.Color(0, 0, 153));
        cand2.setText("NOMBRE CANDIDATO 2");
        cand2.setContentAreaFilled(false);
        cand2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cand2ActionPerformed(evt);
            }
        });
        getContentPane().add(cand2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        cand3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cand3.setForeground(new java.awt.Color(0, 0, 153));
        cand3.setText("NOMBRE CANDIDATO 3");
        cand3.setContentAreaFilled(false);
        cand3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cand3ActionPerformed(evt);
            }
        });
        getContentPane().add(cand3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        empresa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        empresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/logo1.png"))); // NOI18N
        getContentPane().add(empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        buscar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/buscar.png"))); // NOI18N
        buscar2.setContentAreaFilled(false);
        getContentPane().add(buscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, -1, 70, 50));
        getContentPane().add(buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 150, 30));

        principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/tie.png"))); // NOI18N
        principal.setContentAreaFilled(false);
        principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principalActionPerformed(evt);
            }
        });
        getContentPane().add(principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/add.png"))); // NOI18N
        crear.setContentAreaFilled(false);
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });
        getContentPane().add(crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, -1));

        perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/no_profile.png"))); // NOI18N
        perfil.setContentAreaFilled(false);
        perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilActionPerformed(evt);
            }
        });
        getContentPane().add(perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));

        menu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo1.png"))); // NOI18N
        menu1.setText("jLabel1");
        getContentPane().add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 350, 62));

        menu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo1.png"))); // NOI18N
        menu2.setText("jLabel1");
        getContentPane().add(menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 50));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principalActionPerformed
        interfazPrincipal a = new interfazPrincipal(this.ctrl);
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_principalActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        interfazEditarOferta c = new interfazEditarOferta(this.ctrl);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_crearActionPerformed

    private void perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilActionPerformed
        interfazPerfil a = new interfazPerfil(this.ctrl);
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_perfilActionPerformed

    private void cand1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cand1ActionPerformed
        interfazVerPerfil f = new interfazVerPerfil(this.ctrl);
        f.setVisible(true);
        
    }//GEN-LAST:event_cand1ActionPerformed

    private void cand2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cand2ActionPerformed
        interfazVerPerfil f = new interfazVerPerfil(this.ctrl);
        f.setVisible(true);
        
    }//GEN-LAST:event_cand2ActionPerformed

    private void cand3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cand3ActionPerformed
        interfazVerPerfil f = new interfazVerPerfil(this.ctrl);
        f.setVisible(true);
        
    }//GEN-LAST:event_cand3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazCandidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazCandidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazCandidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazCandidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      /*  java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazCandidatos().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscar1;
    private javax.swing.JButton buscar2;
    private javax.swing.JButton cand1;
    private javax.swing.JButton cand2;
    private javax.swing.JButton cand3;
    private javax.swing.JButton cont1;
    private javax.swing.JButton cont2;
    private javax.swing.JButton cont3;
    private javax.swing.JButton crear;
    private javax.swing.JLabel empresa;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel menu1;
    private javax.swing.JLabel menu2;
    private javax.swing.JButton perfil;
    private javax.swing.JButton principal;
    // End of variables declaration//GEN-END:variables
}
