
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.Image;
import java.awt.Toolkit;
/**
 *
 * @author iker
 */
public class interfazLogin extends javax.swing.JFrame{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
        private Controlador ctrl;
	/**
     * Creates new form interfaz
     */
     public interfazLogin() {
    	//this.ctrl = ctrl;
        initComponents();
        this.setLocationRelativeTo(null);
    }
        
    public interfazLogin(Controlador ctrl) {
    	this.ctrl = ctrl;
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagen/logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        contrasenia = new javax.swing.JLabel();
        textouser = new javax.swing.JTextField();
        textopass = new javax.swing.JPasswordField();
        sesion = new javax.swing.JButton();
        registro = new javax.swing.JButton();
        olvidar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 70, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/logo.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        usuario.setBackground(new java.awt.Color(255, 255, 255));
        usuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setText("Usuario: ");
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        contrasenia.setBackground(new java.awt.Color(255, 255, 255));
        contrasenia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        contrasenia.setForeground(new java.awt.Color(255, 255, 255));
        contrasenia.setText("Contraseña: ");
        getContentPane().add(contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        textouser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textouser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textouserActionPerformed(evt);
            }
        });
        getContentPane().add(textouser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 160, -1));

        textopass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(textopass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 160, -1));

        sesion.setBackground(new java.awt.Color(0, 0, 0));
        sesion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sesion.setForeground(new java.awt.Color(255, 255, 255));
        sesion.setText("Iniciar Sesión");
        sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sesionActionPerformed(evt);
            }
        });
        getContentPane().add(sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        registro.setBackground(new java.awt.Color(0, 0, 0));
        registro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        registro.setForeground(new java.awt.Color(255, 255, 255));
        registro.setText("Crear Cuenta");
        registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroActionPerformed(evt);
            }
        });
        getContentPane().add(registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 120, -1));

        olvidar.setBackground(new java.awt.Color(0, 0, 0));
        olvidar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        olvidar.setForeground(new java.awt.Color(255, 255, 255));
        olvidar.setText("¿Contraseña olvidada?");
        olvidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                olvidarActionPerformed(evt);
            }
        });
        getContentPane().add(olvidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo1.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //salir
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    //loguear
    private void sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sesionActionPerformed
        this.ctrl.actionPerformed(evt);
    }//GEN-LAST:event_sesionActionPerformed

    //ir a la pagina de registro
    private void registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroActionPerformed
    	this.ctrl.actionPerformed(evt);
    }//GEN-LAST:event_registroActionPerformed

    //olvidada contrasenya
    private void olvidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_olvidarActionPerformed
        interfazAux c = new interfazAux();
        c.setVisible(true);
    }//GEN-LAST:event_olvidarActionPerformed

    private void textouserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textouserActionPerformed

    }//GEN-LAST:event_textouserActionPerformed

    public void setController(Controlador c){
        this.ctrl = c;
    }

    public String getTextoUsuario(){
        return textouser.getText();
    }
    
    public String getTextoContrasenia(){
        return textopass.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contrasenia;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton olvidar;
    private javax.swing.JButton registro;
    private javax.swing.JButton sesion;
    private javax.swing.JPasswordField textopass;
    private javax.swing.JTextField textouser;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables



}