/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author iker
 */
public class interfazPerfil extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
	private Controlador ctrl;
    public interfazPerfil(Controlador ctrl) {
    	this.ctrl = ctrl;
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagen/logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foto = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        ciudad = new javax.swing.JLabel();
        oferta = new javax.swing.JButton();
        log = new javax.swing.JButton();
        crear = new javax.swing.JButton();
        candidatos = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        misofertas = new javax.swing.JButton();
        historial = new javax.swing.JButton();
        valor = new javax.swing.JButton();
        chat = new javax.swing.JButton();
        perfil2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        principal = new javax.swing.JButton();
        perfil = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        nombreoferta = new javax.swing.JLabel();
        editar = new javax.swing.JButton();
        trabajador = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        editar2 = new javax.swing.JLabel();
        trabajador2 = new javax.swing.JLabel();
        cerrar2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(350, 480));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(350, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/photo.png"))); // NOI18N
        getContentPane().add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nombre.setText("NOMBRE OFERTANTE");
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        ciudad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ciudad.setText("CIUDAD");
        getContentPane().add(ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        oferta.setBackground(new java.awt.Color(0, 204, 0));
        oferta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        oferta.setForeground(new java.awt.Color(255, 255, 255));
        oferta.setText("Crear oferta");
        oferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ofertaActionPerformed(evt);
            }
        });
        getContentPane().add(oferta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 110, -1));

        log.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/log.png"))); // NOI18N
        log.setContentAreaFilled(false);
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });
        getContentPane().add(log, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 30, -1));

        crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/add.png"))); // NOI18N
        crear.setContentAreaFilled(false);
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });
        getContentPane().add(crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, -1));

        candidatos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        candidatos.setForeground(new java.awt.Color(0, 0, 204));
        candidatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/trabajador.png"))); // NOI18N
        candidatos.setContentAreaFilled(false);
        candidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidatosActionPerformed(evt);
            }
        });
        getContentPane().add(candidatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 40, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 20, 140));

        misofertas.setBackground(new java.awt.Color(153, 153, 153));
        misofertas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        misofertas.setForeground(new java.awt.Color(0, 51, 153));
        misofertas.setText("Mis Ofertas");
        misofertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                misofertasActionPerformed(evt);
            }
        });
        getContentPane().add(misofertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 100, -1));

        historial.setBackground(new java.awt.Color(153, 153, 153));
        historial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        historial.setForeground(new java.awt.Color(0, 51, 153));
        historial.setText("Historial");
        historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialActionPerformed(evt);
            }
        });
        getContentPane().add(historial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 100, -1));

        valor.setBackground(new java.awt.Color(153, 153, 153));
        valor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        valor.setForeground(new java.awt.Color(0, 51, 153));
        valor.setText("Valoraciones");
        valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorActionPerformed(evt);
            }
        });
        getContentPane().add(valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 100, -1));

        chat.setBackground(new java.awt.Color(153, 153, 153));
        chat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chat.setForeground(new java.awt.Color(0, 51, 153));
        chat.setText("Chat");
        chat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatActionPerformed(evt);
            }
        });
        getContentPane().add(chat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 100, -1));

        perfil2.setBackground(new java.awt.Color(0, 102, 102));
        perfil2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        perfil2.setForeground(new java.awt.Color(255, 255, 255));
        perfil2.setText("Editar Perfil");
        perfil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfil2ActionPerformed(evt);
            }
        });
        getContentPane().add(perfil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 110, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 100, 10));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/pago.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 40, 30));

        principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/tie.png"))); // NOI18N
        principal.setContentAreaFilled(false);
        principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principalActionPerformed(evt);
            }
        });
        getContentPane().add(principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/no_profile.png"))); // NOI18N
        perfil.setContentAreaFilled(false);
        getContentPane().add(perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Candidatos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("Pagar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo1.png"))); // NOI18N
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 350, 62));

        nombreoferta.setBackground(new java.awt.Color(0, 0, 0));
        nombreoferta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nombreoferta.setText("NOMBRE DE LA OFERTA");
        getContentPane().add(nombreoferta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/edit.png"))); // NOI18N
        editar.setContentAreaFilled(false);
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        getContentPane().add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 40, 30));

        trabajador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/grupo.png"))); // NOI18N
        trabajador.setContentAreaFilled(false);
        trabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trabajadorActionPerformed(evt);
            }
        });
        getContentPane().add(trabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 40, 30));

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/cancel.png"))); // NOI18N
        cerrar.setContentAreaFilled(false);
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 40, 30));

        editar2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        editar2.setForeground(new java.awt.Color(0, 153, 0));
        editar2.setText("Editar");
        getContentPane().add(editar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        trabajador2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        trabajador2.setForeground(new java.awt.Color(0, 0, 204));
        trabajador2.setText("Trabajadores");
        getContentPane().add(trabajador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        cerrar2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cerrar2.setForeground(new java.awt.Color(255, 0, 0));
        cerrar2.setText("Cerrar");
        getContentPane().add(cerrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principalActionPerformed
        interfazPrincipal a = new interfazPrincipal(this.ctrl);
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_principalActionPerformed

    private void ofertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ofertaActionPerformed
        interfazEditarOferta c = new interfazEditarOferta(this.ctrl);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ofertaActionPerformed

    private void perfil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfil2ActionPerformed
        interfazEditarPerfil b = new interfazEditarPerfil(this.ctrl);
        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_perfil2ActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        interfazEditarOferta c = new interfazEditarOferta(this.ctrl);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_editarActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        interfazEditarOferta c = new interfazEditarOferta(this.ctrl);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_crearActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        interfazLogin d = new interfazLogin(this.ctrl);
        d.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logActionPerformed

    private void misofertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_misofertasActionPerformed
        interfazAux e = new interfazAux();
        e.setVisible(true);
    }//GEN-LAST:event_misofertasActionPerformed

    private void historialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialActionPerformed
        interfazAux e = new interfazAux();
        e.setVisible(true);
    }//GEN-LAST:event_historialActionPerformed

    private void valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorActionPerformed
        interfazAux e = new interfazAux();
        e.setVisible(true);
    }//GEN-LAST:event_valorActionPerformed

    private void chatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatActionPerformed
        interfazAux e = new interfazAux();
        e.setVisible(true);
    }//GEN-LAST:event_chatActionPerformed

    private void trabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trabajadorActionPerformed
        interfazCandidatos g = new interfazCandidatos(this.ctrl);
        g.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_trabajadorActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        interfazAux e = new interfazAux();
        e.setVisible(true);
    }//GEN-LAST:event_cerrarActionPerformed

    private void candidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidatosActionPerformed
        interfazTrabajadores f = new interfazTrabajadores(this.ctrl);
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_candidatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
      /*  java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazPerfil().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton candidatos;
    private javax.swing.JButton cerrar;
    private javax.swing.JLabel cerrar2;
    private javax.swing.JButton chat;
    private javax.swing.JLabel ciudad;
    private javax.swing.JButton crear;
    private javax.swing.JButton editar;
    private javax.swing.JLabel editar2;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel foto;
    private javax.swing.JButton historial;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton log;
    private javax.swing.JLabel menu;
    private javax.swing.JButton misofertas;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel nombreoferta;
    private javax.swing.JButton oferta;
    private javax.swing.JButton perfil;
    private javax.swing.JButton perfil2;
    private javax.swing.JButton principal;
    private javax.swing.JButton trabajador;
    private javax.swing.JLabel trabajador2;
    private javax.swing.JButton valor;
    // End of variables declaration//GEN-END:variables
}
